In [1]:
import numpy as np 
a = [1,2,3,4,5,6,7,8]
m =  np.amax(a[0:3])
a = np.asarray(a)
a.reshape(2,4)

b= [[6], [6], [6], [6], [6], [6],[7],[8],[9]]

print(b)
b = np.asarray(b)
print(b.shape)
b = b.reshape(3,3)
print(b)
b.shape


[[6], [6], [6], [6], [6], [6], [7], [8], [9]]
(9, 1)
[[6 6 6]
 [6 6 6]
 [7 8 9]]


(3, 3)

In [28]:
x = 1
y  = 2
inds = np.zeros((2,))
inds[0]=x
inds[1]=y
inds1 = [2,3]
inds2 = [4,5]
inds3 = [6,7]
inds4 = [8,9]
indices = []
indices.append(inds)
indices.append(inds1)
indices.append(inds2)
indices.append(inds3)
indices.append(inds4)

In [31]:
indices= np.asarray(indices)
indices.reshape(-1)

array([1., 2., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
a = [1,2,3,4,5,6,7,8]
m = np.argmax(a)

In [20]:
m

7